spring:
  application:
    name: social-media-application

  datasource:
    url: jdbc:postgresql://localhost:5432/social_media_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/social_media_db
    user: postgres
    password: admin
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
#  secret: ${JWT_SECRET:yourSecretKeyHereMustBeLongEnoughForHS512Algorithm}
  secret: secretaryship
  expiration: 3600000 # 1 hour in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Server Configuration
server:
  port: 8090
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always

# Logging
#logging:
#  level:
#    com.appifylab: DEBUG
#    org.springframework.security: DEBUG